### PR TITLE
Add hooks for set type

### PR DESCRIPTION
**Pull request by konradmb**
It's a simple change - I've reused HashSet procs.

During testing I've found a bug with `from jsony import nil` https://github.com/konradmb/jsony/commit/fd08c4e7f9f69c00ba6b1b125ac6f05fcef603b8#diff-2d91982de276dc64eab6f65f18f163e2e279c6e977abb09c0511c7694312f868R73

But you can ignore it for now as it's not connected to this change.

### CODE REVIEW

**Comment by treeform** [comment]
Thank you for this PR!

The file tests/test_set_import_nil.nim appears to be a duplicate of the other file. Please remove it for now and I'll merge this PR.

We can take a look about `import nil` in another pr.

**Comment by konradmb** [comment]
Ok, done

**Comment by treeform** [comment]
Thank you! Merged.

**Comment by treeform** [comment]
I made some changes, I merge the test_set and test_sets file, and created my own version of SomeSet that includes set and just used that. https://github.com/treeform/jsony/commit/ebee42e04b13c851ee7175b757fc00868f2a5921

**Comment by konradmb** [comment]
Ok, looks cleaner

**Pull request merged**
